# Base Image.
FROM ubuntu:16.04

# Owner 
MAINTAINER Amit Vashist <amitvashist7@gmail.com>

# Update the APT Repo. 
RUN apt-get update

#Install Apache Packages.
RUN apt-get install apache2 -y 

# Copy the Code. 
COPY info.html /var/www/html/

EXPOSE 80 8080

# Excute the Service 
CMD ["/usr/sbin/apache2ctl", "-D", "FOREGROUND"]
